[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_airdrop = "AfZt7zP6v3sBh4JjyjuEvmf4iRnhkaK8xYiim4tkZMAj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
